name: Manual CRAN Release Tagger

on:
  workflow_dispatch: # Activates the manual button in the GitHub UI

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from DESCRIPTION
        id: get_version
        run: |
          VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            Official release of version ${{ steps.get_version.outputs.VERSION }} on CRAN.
          draft: false
          prerelease: false
